#scr drew_point,line,circle,board and mouse operation

func=main.c init_scr_set.c basic_op.c mouse_op.c
para=-o main -Wall
main:$(func)
	gcc $(func) $(para)
clean:
	rm -rf main
	rm -rf *.o
	rm -rf ~*
